apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: airflow-create-watch
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "airflow.fullname" . }}-ns-access
  labels:
    app: {{ template "airflow.name" . }}-scheduler
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: {{ template "airflow.fullname" . }}-ns-access
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: airflow-create-watch
  apiGroup: rbac.authorization.k8s.io
